import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		
		//Initialize variables for a single experiment
		Boolean IsBoy = false;
		Boolean IsGirl = false;
		int NumOfChildrenSingleEx = 0;
		
		//Initialize variables for all experiments
		int TwoChildrenCount = 0;
		int ThreeChildrenCount = 0;
		int FourOrMoreChildrenCount = 0;
		double NumOfChildrenOverall = 0;
		String MostCommonNumOfChildren = "";
		
		for (int i = 0; i < T; i++)
		{
			IsBoy = false;
			IsGirl = false;
			NumOfChildrenSingleEx = 0;
			while (!IsBoy || !IsGirl)
			{
				if (generator.nextDouble() < 0.5)
				{
					IsBoy = true;
				}
				else
				{
					IsGirl = true;
				}
				NumOfChildrenSingleEx++;
			}
			if (NumOfChildrenSingleEx == 2) TwoChildrenCount++;
			else if (NumOfChildrenSingleEx == 3) ThreeChildrenCount++;
			else FourOrMoreChildrenCount++;
			NumOfChildrenOverall += NumOfChildrenSingleEx;
		}
		
		System.out.println("Average: " + (NumOfChildrenOverall / T) + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + TwoChildrenCount);
		System.out.println("Number of families with 3 children: " + ThreeChildrenCount);
		System.out.println("Number of families with 4 or more children: " + FourOrMoreChildrenCount);
		
		MostCommonNumOfChildren = "4 or more.";
		if (ThreeChildrenCount >= Math.max(TwoChildrenCount, FourOrMoreChildrenCount)) MostCommonNumOfChildren = "3.";
		if (TwoChildrenCount >= Math.max(ThreeChildrenCount, FourOrMoreChildrenCount)) MostCommonNumOfChildren = "2.";
		System.out.println("The most common number of children is " + MostCommonNumOfChildren);
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
